### ISSUE TITLE
Network bandwidth meter shows wrong data when connected to Adguard vpn

### ISSUE THREAD

**Issue by techIndia-hacker** [liyafe1997/CustoMIUIzerMod#1]
**Phone Model, Android & MIUI Version:**
 - Phone: redmi note 9 pro
 - Android: 11
 - MIUI: 12.5.3

**Describe the problem**
https://github.com/GravityBox/GravityBox/issues/2087
Please follow this issue. Solution was also provided at the end of the discussion. The developer of the original customiuizer also took part in this conversation

**Comment by liyafe1997** [comment]
Thank you. I will consider this solution in next version.

**Comment by liyafe1997** [comment]
Fixed.
