### ISSUE TITLE
没人发现toast不显示了吗，无论toast项目下有无改动

### ISSUE THREAD

**Issue by 180ENG** [liyafe1997/CustoMIUIzerMod#11]
**Phone Model, Android & MIUI Version:**
 - Phone: 小米平板5pro
 - Android: 11
 - MIUI: 13

希望可以修复“toast”相关模块

**Comment by IcicleCN** [comment]
> **手机型号，Android和MIUI版本：**
> 
> * 电话： 小米平板5pro
> * 安卓： 11
> * MIUI： 13
> 
> 希望可以修复“toast”相关模块

我是红米9 MIUI12.5 Android11的设备，LSP里给CustoMIUIzer勾选要生效的app后，toast相关设置才生效了，兄弟你参考一下

**Comment by liyafe1997** [comment]
Toast需要把作用域应用到对应的App上
