### ISSUE TITLE
Bug: Statusbar clock with seconds

### ISSUE THREAD

**Issue by Cutleast** [liyafe1997/CustoMIUIzerMod#21]
**Phone Model, Android & MIUI Version:**
 - Phone: Redmi Note 9 (merlin)
 - Android: 11
 - MIUI: 12.5.4.0 RJOMIXM

**Describe the problem**
In the notification and control center the year in the date is replaced by the seconds of the clock.

**Screenshots**
![Screenshot_2022-07-07-17-41-32-881_com.miui.home~2.jpg](https://user-images.githubusercontent.com/51865074/177816237-90900c56-1107-45f7-9cb0-1a00b086d564.jpg)

**Related APK upload**
If you know where is this mod related to (E.g. systemui) and know how to extract the APK, you can upload it here.
n/a

**LSPosed/EdXposed Log**
It's recommended to upload xposed logs.
[Logs at Google Drive](https://drive.google.com/file/d/1-qr-Z6bWWbPnlcEUsQ7L8SSP_m2q_voN/view?usp=drivesdk)

**Comment by liyafe1997** [comment]
Will be fix on next version.
