### ISSUE TITLE
Bug of VPN icon

### ISSUE THREAD

**Issue by jackskyip** [liyafe1997/CustoMIUIzerMod#25]
**Phone Model, Android & MIUI Version:**
 - Phone: Mi 9T Pro
 - Android: 11
 - MIUI: 12.5

**Describe the problem**
A clear and concise description of what the problem is.
The VPN icon still shows in the status bar after setting to hide the icon.

**Screenshots**
![IMG_20220720_162002](https://user-images.githubusercontent.com/49543516/179945101-687f317d-8846-4b7e-ac40-4dbd4b377e3a.jpg)

**Related APK upload**
If you know where is this mod related to (E.g. systemui) and know how to extract the APK, you can upload it here.

**LSPosed/EdXposed Log**
It's recommended to upload xposed logs.

**Comment by liyafe1997** [comment]
Will be fix in next version
