### ISSUE TITLE
Hiding the wifi icon doesn't work

### ISSUE THREAD

**Issue by mindblower1504** [liyafe1997/CustoMIUIzerMod#28]
**Phone Model, Android & MIUI Version:**
 - Phone: Redmi Note 8
 - Android: 11
 - MIUI: 12.5

Hiding the wifi icon doesn't work 

![IMG_20220825_180320](https://user-images.githubusercontent.com/112106444/186714469-d4abc313-e5a6-4ba8-9f08-7476deca4b9a.jpg)

**Comment by grappas** [comment]
No hiding actually works.

Redmi Note 9S
Android 11
MIUI 12.5

**Comment by liyafe1997** [comment]
Will be fix in next version
