### ISSUE TITLE
解锁动画不生效

### ISSUE THREAD

**Issue by ghost** [liyafe1997/CustoMIUIzerMod#3]
**Phone Model, Android & MIUI Version:**
 - Phone: 红米k20PRO
 - Android: 安卓11
 - MIUI: 12.5

**Describe the problem**
A clear and concise description of what the problem is.
解锁动画已经关闭了，但还是有解锁动画，而且打开软件的时候还提示我没安装lsposed
**Screenshots**

**Related APK upload**
If you know where is this mod related to (E.g. systemui) and know how to extract the APK, you can upload it here.

**LSPosed/EdXposed Log**
It's recommended to upload xposed logs.

**Comment by liyafe1997** [comment]
Fixed.
