### ISSUE TITLE
VPN icon not hide

### ISSUE THREAD

**Issue by rafizulhasan** [liyafe1997/CustoMIUIzerMod#45]
**Phone Model, Android & MIUI Version:**
 - Phone: k20 pro
 - Android: 11
 - MIUI: 12.5

**Describe the problem**
A clear and concise description of what the problem is.

**Screenshots**

**Related APK upload**
If you know where is this mod related to (E.g. systemui) and know how to extract the APK, you can upload it here.

**LSPosed/EdXposed Log**
It's recommended to upload xposed logs.

**Comment by liyafe1997** [comment]
Will be fix in next version
