### ISSUE TITLE
There is a second counter adjacent to the date.

### ISSUE THREAD

**Issue by cihaneken** [liyafe1997/CustoMIUIzerMod#48]
**Phone Model, Android & MIUI Version:**
 - Phone:  Mi 9
 - Android: A11
 - MIUI:  12.5.2 Official 

**Describe the problem**
There is a second counter adjacent to the date.  It is unknown what purpose it served.

**Screenshots**
![IMG_20230326_183248](https://user-images.githubusercontent.com/17432022/227790421-3615b525-ea13-431e-b447-cbb135469d33.jpg)

**Related APK upload**

1.6.321

**LSPosed/EdXposed Log**
Null

**Comment by liyafe1997** [comment]
Will be fix on next version.
