### ISSUE TITLE
“状态栏显示秒”“扩展通知菜单”“扩展电源菜单”等三项功能不生效

### ISSUE THREAD

**Issue by cynosure1993** [liyafe1997/CustoMIUIzerMod#6]
**Phone Model, Android & MIUI Version:**
 - Phone: 小米MIX4
 - Android: 11
 - MIUI: 12.5.12

**Describe the problem**
A clear and concise description of what the problem is.
“状态栏显示秒”“扩展通知菜单”“扩展电源菜单”等三项功能不生效，请求修复

**Screenshots**
![IMG_20220511_021748](https://user-images.githubusercontent.com/20870427/167697485-a416d66b-849c-4892-9551-40215b47109b.jpg)
![IMG_20220511_021713](https://user-images.githubusercontent.com/20870427/167697518-8483e2bf-f74b-4405-aa7c-a8c111440465.jpg)
![IMG_20220511_021622](https://user-images.githubusercontent.com/20870427/167697595-25d41f9a-0118-49a4-b85a-efcfe1fd6205.jpg)

**Related APK upload**
If you know where is this mod related to (E.g. systemui) and know how to extract the APK, you can upload it here.

**LSPosed/EdXposed Log**
It's recommended to upload xposed logs.
[LSPosed_2022-05-11T02_35_37.993.zip](https://github.com/liyafe1997/CustoMIUIzerMod/files/8664151/LSPosed_2022-05-11T02_35_37.993.zip)

**Comment by liyafe1997** [comment]
状态栏显示秒将在下一个版本修复
关于扩展通知菜单和扩展电源菜单，因为在MIUI12+中整个交互逻辑改变了，这两个功能不太好去实现，目前暂时先搁置。

**Comment by liyafe1997** [comment]
Show seconds is fixed on release 1.4.321

**Comment by cynosure1993** [comment]
感谢大佬，辛苦了。
