### ISSUE TITLE
求修复隐藏导航栏功能

### ISSUE THREAD

**Issue by q1332812184** [liyafe1997/CustoMIUIzerMod#7]
**Phone Model, Android & MIUI Version:**
 - Phone: K20 PRO
 - Android: 11
 - MIUI: 12.5.6

**Describe the problem**
翻了酷安几个小时都找不到能屏蔽导航栏的方案，以前一直用的custoMIUI，换手机发现这软件功能失效了。。用了你的版本发现也是未修复的

**Screenshots**
![Screenshot_2022-05-11-02-49-34-272_org strawing customiuizermod](https://user-images.githubusercontent.com/79078829/167701103-73204ffa-184f-4025-a568-cf5c92228d6b.jpg)

**Related APK upload**
If you know where is this mod related to (E.g. systemui) and know how to extract the APK, you can upload it here.

**LSPosed/EdXposed Log**
It's recommended to upload xposed logs.

**Comment by liyafe1997** [comment]
能否上传下LSPosed Log？谢谢

**Comment by liyafe1997** [comment]
Fixed on release 1.4.321
