### ISSUE TITLE
Battery bar mod doesn't work on miui 12.5.

### ISSUE THREAD

**Issue by Motisu** [liyafe1997/CustoMIUIzerMod#8]
I installed on a poco x3 nfc running xiaomi.eu. The mod is active in lsposed (zygisk version) but the battery bar doesn't work.

**Comment by liyafe1997** [comment]
Can you submit the lsposed log? Thank you!

**Comment by Motisu** [comment]
Sure, if you tell me where to find it.
Thank you for responding so fast!

Thanks,

Moti Susswein

Sent from my Android; Please excuse any typos.

________________________________

**Comment by liyafe1997** [comment]
Fixed on release 1.4.321

**Comment by Motisu** [comment]
Thank you for the fix, but there is a small problem.  The old version was visible all the time, this new one is only visible when the status bar is visible. I use Nova 7 launcher and when the launcher is open, I have it set so that the status bar is closed, so the bar disappears.  ATM, I will leave the status bar in Nova open, but is there any way of making it stay visible all the time?

**Comment by Motisu** [comment]
Please disregard my last message. I found the log and am sending it to you.



Thanks,

Moti

P Please consider your environmental responsibility before printing this e-mail
